export type FreeEcommerceSeedProduct = {
  id: string;
  image: string;
  name: string;
  rating: {
    stars: number;
    count: number;
  };
  priceCents: number;
  category: string;
  subCategory: string;
  keywords: string[];
  description: string;
};

const IMG = "https://kolzsticks.github.io/Free-Ecommerce-Products-Api/main/images/products";

export const FREE_ECOMMERCE_SEED_PRODUCTS: FreeEcommerceSeedProduct[] = [
  ["1", "moisturizer.jpg", "Hydrating Facial Moisturizer", 4.7, 120, 2000, "Beauty & Personal Care", "Skincare", ["moisturizer", "hydration", "skincare", "beauty"], "This Hydrating Facial Moisturizer is expertly formulated to deeply nourish and hydrate your skin, providing lasting moisture and a smooth, radiant complexion. Ideal for daily use."],
  ["2", "shampoo.jpg", "Anti-Dandruff Shampoo", 4.5, 85, 1500, "Beauty & Personal Care", "Hair Care", ["shampoo", "hair care", "anti-dandruff", "cleanse"], "Our Anti-Dandruff Shampoo effectively combats flakes and itchiness, promoting a healthy scalp. Infused with soothing ingredients, it cleanses your hair without stripping natural oils."],
  ["3", "foundation.jpg", "Matte Liquid Foundation", 4.6, 98, 2200, "Beauty & Personal Care", "Makeup", ["foundation", "makeup", "beauty", "matte"], "This Matte Liquid Foundation offers a flawless finish with long-lasting wear. Lightweight and breathable, it blends seamlessly into the skin, providing even coverage and a natural look."],
  ["4", "perfume.jpg", "Eau de Parfum - Floral Scent", 4.8, 160, 3500, "Beauty & Personal Care", "Fragrances", ["perfume", "fragrance", "scent", "floral"], "Experience the essence of blooming florals with our Eau de Parfum. This captivating scent envelops you in elegance, making it perfect for any occasion, leaving a lasting impression."],
  ["5", "shaving-kit.jpg", "Men's Shaving Kit", 4.4, 70, 1800, "Beauty & Personal Care", "Grooming", ["shaving kit", "grooming", "men", "razor"], "This Men's Shaving Kit includes everything needed for a close, comfortable shave. Featuring a premium razor and soothing gel, it ensures a smooth experience with every use."],
  ["6", "body-wash.jpg", "Nourishing Body Wash", 4.7, 140, 1300, "Beauty & Personal Care", "Bath & Body", ["body wash", "bath", "care", "nourishing"], "Our Nourishing Body Wash gently cleanses while replenishing moisture, leaving your skin feeling soft and revitalized. Infused with natural ingredients for a refreshing bathing experience."],
  ["7", "nail-polish.jpg", "Glossy Nail Polish", 4.5, 65, 800, "Beauty & Personal Care", "Nail Care", ["nail polish", "nail care", "beauty", "glossy"], "Achieve stunning nails with our Glossy Nail Polish. This vibrant formula provides high shine and long-lasting wear, perfect for expressing your personal style with every application."],
  ["8", "conditioner.jpg", "Moisturizing Conditioner", 4.6, 110, 1700, "Beauty & Personal Care", "Hair Care", ["conditioner", "hair care", "moisturizing", "smooth"], "Our Moisturizing Conditioner deeply hydrates and detangles hair, leaving it soft, shiny, and manageable. Perfect for all hair types, it helps restore natural moisture balance."],
  ["9", "razor.jpg", "Triple Blade Razor", 4.3, 55, 1000, "Beauty & Personal Care", "Men's Grooming Products", ["razor", "grooming", "men", "shaving"], "The Triple Blade Razor delivers an exceptionally close shave with minimal irritation. Its ergonomic design provides comfort and control, making it a must-have for every grooming routine."],
  ["10", "vitamin-supplement.jpg", "Vitamin C Supplement", 4.7, 200, 3000, "Beauty & Personal Care", "Health & Wellness Products", ["vitamin c", "supplement", "wellness", "health"], "Boost your health with our Vitamin C Supplement. Designed to support immune function and overall wellness, these easy-to-take tablets provide essential nutrients for your daily needs."],
  ["11", "wireless-headphones.jpg", "Wireless Bluetooth Headphones", 4.7, 230, 7999, "Electronics & Gadgets", "Audio", ["headphones", "bluetooth", "audio", "electronics"], "Experience superior sound quality with these wireless Bluetooth headphones, designed for comfort and portability for everyday use."],
  ["12", "smartphone.jpg", "Smartphone - 128GB", 4.6, 320, 45000, "Electronics & Gadgets", "Mobile Phones", ["smartphone", "mobile", "gadgets"], "Stay connected with this high-performance smartphone featuring 128GB storage, perfect for apps, photos, and multimedia."],
  ["13", "4k-tv.jpg", "55-Inch 4K Ultra HD TV", 4.8, 190, 90000, "Electronics & Gadgets", "Televisions", ["television", "4K", "electronics", "gadgets"], "Enjoy breathtaking visuals with this 55-inch 4K Ultra HD TV, delivering stunning detail and vibrant colors for your favorite shows."],
  ["14", "laptop.jpg", "Gaming Laptop - 16GB RAM, 512GB SSD", 4.9, 210, 120000, "Electronics & Gadgets", "Computers", ["laptop", "gaming", "computers", "electronics"], "Unleash your gaming potential with this powerful gaming laptop featuring 16GB RAM and 512GB SSD for speed and performance."],
  ["15", "smartwatch.jpg", "Smartwatch - Fitness Tracker", 4.5, 130, 15000, "Electronics & Gadgets", "Wearables", ["smartwatch", "fitness", "wearables", "electronics"], "Monitor your health and stay connected with this feature-rich smartwatch, perfect for tracking fitness and receiving notifications."],
  ["16", "tablet.jpg", "10.1-Inch Android Tablet", 4.3, 95, 20000, "Electronics & Gadgets", "Tablets", ["tablet", "android", "gadgets", "electronics"], "Enjoy your favorite apps and media on this sleek 10.1-inch Android tablet, offering portability and a vibrant display for on-the-go."],
  ["17", "bluetooth-speaker.jpg", "Portable Bluetooth Speaker", 4.7, 180, 5000, "Electronics & Gadgets", "Audio", ["bluetooth", "speaker", "audio", "gadgets"], "Take your music anywhere with this portable Bluetooth speaker, delivering powerful sound in a compact design, perfect for outdoor use."],
  ["18", "dslr-camera.jpg", "DSLR Camera - 24MP", 4.8, 115, 85000, "Electronics & Gadgets", "Cameras", ["camera", "dslr", "gadgets", "electronics"], "Capture stunning photos and videos with this 24MP DSLR camera, offering professional-quality imaging and advanced features for creatives."],
  ["19", "usb-drive.jpg", "USB Drive - 64GB", 4.2, 75, 1200, "Electronics & Gadgets", "Storage", ["usb", "storage", "gadgets", "electronics"], "Store and transfer your files easily with this 64GB USB drive, offering ample space and portability for your data needs."],
  ["20", "action-camera.jpg", "4K Action Camera", 4.6, 90, 18000, "Electronics & Gadgets", "Cameras", ["action camera", "4K", "gadgets", "electronics"], "Record your adventures in stunning detail with this 4K action camera, built to withstand tough conditions and capture high-quality footage."],
  ["21", "denim-jacket.jpg", "Men's Denim Jacket", 4.5, 150, 3500, "Fashion & Apparel", "Men's Clothing", ["denim jacket", "men's fashion", "clothing", "outerwear"], "This stylish Men's Denim Jacket is perfect for any casual occasion. Crafted from high-quality denim, it features a classic fit, button closure, and timeless design that complements various outfits."],
  ["22", "maxi-dress.jpg", "Women's Floral Maxi Dress", 4.8, 95, 4200, "Fashion & Apparel", "Women's Clothing", ["floral dress", "women's fashion", "clothing", "dress"], "Embrace elegance with this Women's Floral Maxi Dress, designed with a flattering silhouette and vibrant floral patterns. Perfect for sunny days and special occasions, it's a must-have addition to your wardrobe."],
  ["23", "sneakers.jpg", "Unisex Casual Sneakers", 4.7, 210, 5500, "Fashion & Apparel", "Footwear", ["sneakers", "footwear", "shoes", "casual"], "These Unisex Casual Sneakers blend comfort and style effortlessly. With a lightweight design and cushioned sole, they're perfect for everyday wear, making them a versatile choice for any outfit."],
  ["24", "leather-bag.jpg", "Leather Tote Bag", 4.6, 130, 6000, "Fashion & Apparel", "Accessories", ["leather bag", "tote", "accessories", "fashion"], "Elevate your style with this chic Leather Tote Bag, featuring a spacious interior and elegant design. Crafted from premium leather, it's perfect for carrying your essentials while looking effortlessly stylish."],
  ["25", "sunglasses.jpg", "Polarized Sunglasses", 4.4, 90, 2500, "Fashion & Apparel", "Accessories", ["sunglasses", "polarized", "accessories", "fashion"], "Protect your eyes in style with these Polarized Sunglasses. Designed to reduce glare and enhance visual clarity, they offer both comfort and sophistication for all your outdoor adventures."],
  ["26", "formal-shirt.jpg", "Men's Formal Shirt", 4.3, 85, 3100, "Fashion & Apparel", "Men's Clothing", ["formal shirt", "men's fashion", "clothing", "shirt"], "This Men's Formal Shirt combines elegance with comfort. Tailored to perfection, it features a classic collar and a crisp finish, making it the ideal choice for business meetings or formal occasions."],
  ["27", "heels.jpg", "Women's High Heels", 4.6, 105, 4500, "Fashion & Apparel", "Footwear", ["heels", "women's footwear", "fashion", "shoes"], "Step into sophistication with these Women's High Heels, featuring a sleek design and comfortable fit. Perfect for parties, weddings, or a night out, they will elevate any outfit with a touch of glamour."],
  ["28", "t-shirt.jpg", "Graphic Print T-Shirt", 4.5, 200, 1800, "Fashion & Apparel", "Men's Clothing", ["t-shirt", "graphic print", "men's fashion", "clothing"], "Express yourself with this Graphic Print T-Shirt, featuring vibrant colors and unique designs. Made from soft cotton, it offers a relaxed fit, making it perfect for casual outings or lounging at home."],
  ["29", "handbag.jpg", "Women's Designer Handbag", 4.9, 150, 7500, "Fashion & Apparel", "Accessories", ["handbag", "designer", "fashion", "accessories"], "Make a statement with this Women's Designer Handbag, crafted from luxurious materials and featuring exquisite detailing. It's spacious enough for daily essentials while adding elegance to your ensemble."],
  ["30", "slippers.jpg", "Comfortable Flip-Flops", 4.2, 70, 1200, "Fashion & Apparel", "Footwear", ["flip-flops", "slippers", "footwear", "casual"], "Enjoy ultimate comfort with these Comfortable Flip-Flops. Designed for casual wear, they feature soft straps and cushioned soles, making them perfect for the beach, pool, or everyday relaxation."],
  ["31", "sofa.jpg", "Modern Leather Sofa", 4.8, 220, 120000, "Home & Kitchen", "Furniture", ["sofa", "furniture", "living room", "home decor"], "A stylish modern leather sofa that enhances the elegance of your living room while providing utmost comfort for relaxation and entertaining guests."],
  ["32", "refrigerator.jpg", "Stainless Steel Refrigerator", 4.6, 150, 95000, "Home & Kitchen", "Kitchen Appliances", ["refrigerator", "appliance", "kitchen", "stainless steel"], "This sleek stainless steel refrigerator features ample storage space, energy efficiency, and modern technology, making it perfect for keeping your food fresh."],
  ["33", "vacuum-cleaner.jpg", "Cordless Vacuum Cleaner", 4.4, 180, 18000, "Home & Kitchen", "Home Appliances", ["vacuum cleaner", "cordless", "cleaning", "home"], "Enjoy effortless cleaning with this cordless vacuum cleaner, designed for convenience and efficiency, easily reaching corners and tight spaces without any cords."],
  ["34", "cookware.jpg", "Non-Stick Cookware Set", 4.7, 95, 25000, "Home & Kitchen", "Cookware & Bakeware", ["cookware", "non-stick", "kitchen", "bakeware"], "This non-stick cookware set is perfect for easy cooking and cleaning, ensuring your meals come out delicious without sticking, making meal prep a breeze."],
  ["35", "dinnerware.jpg", "Porcelain Dinnerware Set", 4.9, 70, 16000, "Home & Kitchen", "Dinnerware & Serveware", ["dinnerware", "porcelain", "kitchen", "tableware"], "Elevate your dining experience with this exquisite porcelain dinnerware set, perfect for both everyday meals and special occasions, combining elegance and functionality."],
  ["36", "mattress.jpg", "Memory Foam Mattress", 4.8, 140, 75000, "Home & Kitchen", "Bedding", ["mattress", "memory foam", "bedding", "sleep"], "Experience superior comfort with our memory foam mattress, designed to contour to your body and provide excellent support for a restful night's sleep."],
  ["37", "table-lamp.jpg", "Contemporary Table Lamp", 4.5, 85, 5000, "Home & Kitchen", "Lighting", ["lamp", "lighting", "home decor", "table lamp"], "Brighten your space with this contemporary table lamp, combining modern design and functionality, perfect for reading or creating a cozy atmosphere in any room."],
  ["38", "rug.jpg", "Hand-Woven Area Rug", 4.6, 110, 20000, "Home & Kitchen", "Home Decor", ["rug", "home decor", "woven", "area rug"], "This hand-woven area rug adds warmth and style to your home decor, featuring intricate designs that enhance any living space while providing comfort underfoot."],
  ["39", "storage-boxes.jpg", "Plastic Storage Boxes - Set of 4", 4.3, 55, 8000, "Home & Kitchen", "Storage & Organization", ["storage", "organization", "home", "plastic boxes"], "Keep your home organized with this set of 4 plastic storage boxes, perfect for decluttering any space and storing items securely while maintaining easy accessibility."],
  ["40", "cleaning-supplies.jpg", "Eco-Friendly Cleaning Supplies Kit", 4.8, 120, 10000, "Home & Kitchen", "Cleaning Supplies", ["cleaning supplies", "eco-friendly", "home", "cleaning kit"], "This eco-friendly cleaning supplies kit features sustainable products that effectively clean your home while being safe for the environment and your family."],
  ["41", "treadmill.jpg", "Foldable Electric Treadmill", 4.7, 320, 350000, "Health & Fitness", "Fitness Equipment", ["treadmill", "fitness", "exercise", "home gym"], "This Foldable Electric Treadmill offers a convenient way to maintain fitness at home. With various speed settings and a compact design, it's perfect for beginners and seasoned athletes."],
  ["42", "dumbbells.jpg", "Adjustable Dumbbell Set - 20kg", 4.5, 260, 60000, "Health & Fitness", "Fitness Equipment", ["dumbbells", "weights", "fitness", "strength training"], "The Adjustable Dumbbell Set allows for a customizable weight training experience. With a total weight of 20kg, it's perfect for strength training and versatile enough for various workouts."],
  ["43", "protein-powder.jpg", "Whey Protein Powder - 2kg", 4.6, 180, 35000, "Health & Fitness", "Sports Nutrition", ["protein", "nutrition", "supplement", "sports"], "This Whey Protein Powder provides an excellent source of protein for muscle recovery and growth. The 2kg package is ideal for athletes and fitness enthusiasts aiming for optimal nutrition."],
  ["44", "blood-pressure-monitor.jpg", "Digital Blood Pressure Monitor", 4.8, 210, 22000, "Health & Fitness", "Health Monitors", ["blood pressure", "monitor", "health", "medical"], "Stay on top of your health with this Digital Blood Pressure Monitor. Easy to use and highly accurate, it helps you track your blood pressure at home with clear digital readings."],
  ["45", "first-aid-kit.jpg", "Compact First Aid Kit", 4.9, 150, 12000, "Health & Fitness", "First Aid", ["first aid", "kit", "medical", "emergency"], "This Compact First Aid Kit is essential for home, travel, or emergency situations. Packed with necessary supplies, it ensures you're prepared for minor injuries and emergencies."],
  ["46", "hand-sanitizer.jpg", "Alcohol-Based Hand Sanitizer - 500ml", 4.5, 90, 800, "Health & Fitness", "Personal Health", ["hand sanitizer", "personal health", "hygiene", "sanitizer"], "Keep your hands clean and germ-free with this Alcohol-Based Hand Sanitizer. The 500ml bottle is perfect for personal use at home or on the go, providing effective sanitization."],
  ["47", "gloves.jpg", "Workout Gloves - Pair", 4.4, 100, 3000, "Health & Fitness", "Sports Gear & Accessories", ["gloves", "workout", "sports", "fitness"], "Enhance your workout experience with these comfortable Workout Gloves. Designed to provide grip and protection, they are perfect for lifting weights or performing rigorous exercises."],
  ["48", "thermometer.jpg", "Infrared Digital Thermometer", 4.7, 120, 15000, "Health & Fitness", "Health Monitors", ["thermometer", "digital", "health", "infrared"], "This Infrared Digital Thermometer allows for quick and accurate temperature readings. Perfect for home health monitoring, it provides fast results without physical contact."],
  ["49", "yoga-mat.jpg", "Non-Slip Yoga Mat", 4.6, 200, 5000, "Health & Fitness", "Yoga & Meditation Supplies", ["yoga mat", "fitness", "yoga", "exercise"], "The Non-Slip Yoga Mat is designed for stability and comfort during yoga sessions. Its durable material ensures a safe practice, making it ideal for all skill levels and styles."],
  ["50", "knee-pads.jpg", "Adjustable Knee Pads", 4.3, 70, 4000, "Health & Fitness", "Sports Gear & Accessories", ["knee pads", "sports", "gear", "fitness"], "These Adjustable Knee Pads provide comfort and support during workouts. Perfect for protecting your knees during intense activities, they are essential for athletes and fitness lovers."],
].map(([id, file, name, stars, count, priceCents, category, subCategory, keywords, description]) => ({
  id: String(id),
  image: `${IMG}/${file}`,
  name: String(name),
  rating: { stars: Number(stars), count: Number(count) },
  priceCents: Number(priceCents),
  category: String(category),
  subCategory: String(subCategory),
  keywords: keywords as string[],
  description: String(description),
}));
